# Simple image with CMake, make, git and g++
# Credit https://github.com/kracejic/cleanCppProject/blob/master/.gitlab-ci.yml
image: kracejic/alpinecpp

stages:
  - prepare
  - build
  - test
  - package

cache:
  untracked: true
  paths:
    - build
    - external

# Since we are using cache to persist all data, we need to clean in the first
# step.
prepare:
  stage: prepare
  script:
    - git reset --hard HEAD 
    - git clean -d -f -x
    - apt-get update -qq && apt-get install -y libsfml-dev
    - mkdir build
    - cd build
    - cmake ..
    - make external-update-all

build:
  stage: build
  script:
    - cd build
    - make
    - make install

test:
  stage: test
  script:
    - cd build
    # - make check no test yet

package:
  stage: package
  artifacts:
    expire_in: 1 week
    paths:
      - build/out/
  script:
    - cd build
    - make package
