# Simple image with CMake, make, git and g++
image: coignetp/sfml-cmake:latest

stages:
  - prepare
  - build
  - test
  - package

cache:
  untracked: true
  paths:
    - build

prepare:
  stage: prepare
  script:
    - mkdir build
    - cd build
    - cmake ..

build:
  stage: build
  script:
    - cd build
    - cmake --build .

test:
  stage: test
  script:
    - echo "test stage"
    # - make check no test yet

package:
  stage: package
  artifacts:
    expire_in: 1 week
    paths:
      - out/
  script:
    - echo "package stage"
