# Simple image with CMake, make, git and g++
image: coignetp/sfml-cmake:latest

stages:
  - prepare
  - build
  - test
  - package

prepare:
  stage: prepare
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make external-update-all

build:
  stage: build
  script:
    - cd build
    - make
    - make install

test:
  stage: test
  script:
    - cd build
    # - make check no test yet

package:
  stage: package
  artifacts:
    expire_in: 1 week
    paths:
      - build/out/
  script:
    - cd build
    - make package
